DELETE FROM users_events;
ALTER TABLE users_events ALTER COLUMN id RESTART WITH 1;
DELETE FROM films;
ALTER TABLE films ALTER COLUMN id RESTART WITH 1;
DELETE FROM users;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;