DELETE FROM friends;
DELETE FROM likes;
DELETE FROM films_genres;
DELETE FROM films;
ALTER TABLE films ALTER COLUMN id RESTART WITH 1;
DELETE FROM users;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;